language: cpp
dist: trusty

before_install:
  - ./configure.sh

install:
  - sudo apt-get update
  - PWD=$(pwd) && cd /tmp && wget ftp://sourceware.org/pub/valgrind/valgrind-3.13.0.tar.bz2 && tar -xjf valgrind-3.13.0.tar.bz2 && cd valgrind-3.13.0 && ./configure --prefix=/usr/local && make && sudo make install && ccache --clear && valgrind --version && echo $PWD && cd $PWD
  - sudo apt-get install -y libc6-dbg

compiler:
  - clang
  - gcc

script:
  - ./test.sh

after_success:
  - ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
  - ENCRYPTION_LABEL: "1c6c3a1a3c8d"
  - COMMIT_AUTHOR_EMAIL: "agfviggiano@gmail.com"
