language: cpp
dist: trusty

before_install:
  - ./configure.sh

install:
  - sudo apt-get update
  - sudo apt-cache madison valgrind
  - sudo apt-get install -y valgrind

compiler:
  - clang
  - gcc

script:
  - ./test.sh

after_success:
  - ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
  - ENCRYPTION_LABEL: "1c6c3a1a3c8d"
  - COMMIT_AUTHOR_EMAIL: "agfviggiano@gmail.com"
